/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#include "xfce_trayicon.h"

GtkWidget* create_XFCalendar (void);
GtkWidget* create_wAppointment (void);
GtkWidget* create_wInfo (void);
GtkWidget* create_wClearWarn (void);
GtkWidget* create_wReminder (char *text);
XfceTrayIcon* create_TrayIcon (GtkWidget *window);
