/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#include "xfce_trayicon.h"

GtkWidget* create_wAppointment (void);
GtkWidget* create_wClearWarn (GtkWidget *parent);
GtkWidget* recreate_wAppointment (GtkWidget *appointment);
