/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_XFCalendar (void);
GtkWidget* create_wAppointment (void);
GtkWidget* create_wInfo (void);
GtkWidget* create_wClearWarn (void);
