/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_xfce_calendar
#define DBUS_GLIB_CLIENT_WRAPPERS_org_xfce_calendar

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_xfce_calendar_load_file (DBusGProxy *proxy, const char * IN_str, GError **error)

{
  return dbus_g_proxy_call (proxy, "LoadFile", error, G_TYPE_STRING, IN_str, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_xfce_calendar_load_file_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_xfce_calendar_load_file_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_xfce_calendar_load_file_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_xfce_calendar_load_file_async (DBusGProxy *proxy, const char * IN_str, org_xfce_calendar_load_file_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "LoadFile", org_xfce_calendar_load_file_async_callback, stuff, g_free, G_TYPE_STRING, IN_str, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_xfce_calendar */

G_END_DECLS
