.\"     Title: globaltime
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 03/10/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "GLOBALTIME" "1" "03/10/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
globaltime \- International multiclock timeconverter for the Xfce Desktop Environment. It is part of Orage
.SH "SYNOPSIS"
.HP 11
\fBglobaltime\fR
.SH "DESCRIPTION"
.PP

\fBglobaltime\fR
is a fast and easy to use graphical clock for the Xfce Desktop Environment. It can show several clocks in different timezones at the same time. It is also possible to change time, so that it is easier to see when certain time is in other timezones.
\fBglobaltime\fR
is not able to change your operating system time.
.SH "FILES"
.PP
All
\fBglobaltime\fR
datafiles are by default in in
\fI~/.config/globaltime\fR.
.SH "BUGS"
.PP
Please report any bugs and enhancement requests to
\fIhttp://bugzilla.xfce.org/\fR. Note that
\fBglobaltime\fR
is part of
\fBorage\fR
so bugs are reported against orage and component globaltime. Usage related questions can be sent to
\fIxfce@xfce.org\fR
email list.
.SH "HOMEPAGE"
.PP

\fIhttp://www.xfce.org/projects/orage/\fR
.SH "AUTHOR"
.PP

\fBglobaltime\fR
was written by Juha Kautto
<juha@xfce.org>.
.PP
This manual page was written by Juha Kautto
<juha@xfce.org>.
